name: Merge and Deploy

on:
  push:
    branches:
      - dev

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "devandresg"
          git config --global user.email "dev.andres.g@protonmail.com"

      - name: Merge dev into envtest
        run: |
          git checkout envtest
          git merge dev
