name: Merge dev into envtest

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Merge dev into envtest
      run: |
        git config user.name "GitHub Actions"
        git config user.email "dev.andres.g@protonmail.com"
        git fetch origin envtest
        git checkout envtest
        git merge origin/dev --no-commit
        git commit -m "Merge dev into envtest"
        git push origin envtest
