name: Merge dev into envtest

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Merge dev into envtest
      run: |
        ls -la
        git branch -r
        git status
        git checkout envtest
        git pull origin envtest
        git status
        git merge dev --allow-unrelated-histories
        git push origin envtest
